# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpuSimilaridade
                                 A QGIS plugin
 Análise de Similaridade 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-20
        copyright            : (C) 2019 by SPU
        email                : guilherme@dcc.ufmg.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpuSimilaridade class from file SpuSimilaridade.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spu_similaridade import SpuSimilaridade
    return SpuSimilaridade(iface)
