# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpuSimilaridadeDialog
                                 A QGIS plugin
 Análise de Similaridade 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by SPU
        email                : guilherme@dcc.ufmg.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsProject

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'spu_similaridade_dialog_base.ui'))


class SpuSimilaridadeDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__ (self, iface, parent=None):
        """Constructor."""
        super(SpuSimilaridadeDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.iface = iface

        layers = QgsProject.instance().layerTreeRoot().findLayers()
        layer_list = []

        for layer in layers:
            layer_list.append(layer.name())

        self.camada1.addItems(layer_list)
        self.camada2.addItems(layer_list)



